name = "CategoryData"
uuid = "8fccf25a-f50e-468c-8fba-3cb130506274"
authors = ["Lukas Devos", "Jacob Bridgeman"]
version = "0.3.2"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Inflate = "d25df0c9-e2be-5dd7-82c8-3ad0b3e990b9"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SparseArrayKit = "a9a3c162-d163-4c15-8926-b8794fbefed2"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
TensorKitSectors = "13a9c161-d5da-41f0-bcbd-e1a08ae0647f"

[compat]
Downloads = "1"
Inflate = "0.1"
Pkg = "1"
SHA = "0.7, 1"
SparseArrayKit = "0.4"
Tar = "1"
TensorOperations = "5"
TensorKitSectors = "0.1"
TestExtras = "0.2"
julia = "1.10"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestExtras = "5ed8adda-3752-4e41-b88a-e8b09835ee3a"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[targets]
test = ["Test", "TestExtras", "LinearAlgebra", "Random", "TensorOperations"]
